### ISSUE TITLE
Temas para palestras/atividades do CEJS 2018

### ISSUE THREAD

**Issue by ketemartinsrufino** [cejs/cejsconf#1]
Quais temas vocês gostariam de ver nas palestras do CEJS em 2018?
Comente nessa issue com o tema que você gostaria que fosse abordado. 
Escreva um tema por vez, pra ajudar na votação.

Vote com 👍 se gostar de algum tema já proposto, ou poste um novo tema se ainda não existir.

Os temas sugeridos pela comunidade servem de guia para avaliação dos trabalhos submetidos para apresentações na conferência.

O Call For Papers começa em 09 de Abril de 2018.

Em 2017, tivemos votação das apresentações feitas na [LIGHTNING TALKS](http://www.cejs.com.br/#callforpapers)

Participem do Produto Reativo slack (https://produtoreativo.slack.com/)

**Comment by AbraaoAlves** [comment]
Typescript/Flow for Redux apps
Como se beneficiar de tipos em um mundo onde os dados tem um papel central no fluxo da aplicação?

**Comment by mensonones** [comment]
PWA, seus benefícios e futuro

**Comment by cmilfont** [comment]
Server side rendering

**Comment by LucasGabrielSI** [comment]
Introdução ao Node js

**Comment by monycky** [comment]
WebAssembly

**Comment by ypedroo** [comment]
MEAN, PWA

**Comment by helio-frota** [comment]
Do Java ao Node.js - Uma conversa de feedback + visão geral rápida de alguns módulos Node.js da Red Hat.

**Comment by helio-frota** [comment]
Deploy de Node.js Apps no Openshift + O que provê o deploy (por baixo dos panos) ?

**Comment by ketemartinsrufino** [comment]
React Native

**Comment by ketemartinsrufino** [comment]
Linguagens funcionais (ClojureScript, Reason, etc) e como elas interagem com o JS.

**Comment by tsirlucas** [comment]
Técnicas para melhorar a performance da sua aplicação web e como lidar com grandes quantidades de dados

**Comment by tsirlucas** [comment]
Elm

**Comment by ythecombinator** [comment]
Um apanhado sobre modelos e conceitos em concorrência–actors, CSP, futures, streams etc.–explicando contexto que surgiram, como resolviam problemas e comparando abordagens.

**Comment by tsirlucas** [comment]
Immutable.js e seus benefícios

**Comment by tsirlucas** [comment]
Reselect e memoization

**Comment by Ziggoto** [comment]
Blockchain ( Existem uma série de frameworks back-end e front-end para se trabalhar com blockchain )

**Comment by alexmagno** [comment]
RxJS

**Comment by leandrojo** [comment]
Comparatvo Redux-Observable/Redux-Saga (não é obrigatório a estrita colocação do tema comparativo)

**Comment by hugoworks** [comment]
BFF (Backend For Frontend) e GraphQL (Server Engine)

**Comment by AdoniasLemos** [comment]
Algo relacionado ao Dart e o Flutter

**Comment by tsirlucas** [comment]
Testes, qualidade de código e ferramentas de análise e automação e.g. codeclimate, CI's, greenkeeper, etc

**Comment by felipesousa** [comment]
Lit-HTML: Template Rendering JavaScript

**Comment by otalandim** [comment]
Testes em JS

**Comment by wellingtoncosta** [comment]
Apesar de eu achar que já foi encerrado, seria interessante falar sobre Kotlin/JS, elencando os principais pontos da linguagem.

**Comment by ketemartinsrufino** [comment]
Ops... Bem lembrando @WellingtonCosta. Foi encerrado sim, vou fechar a issue. 
Obrigada pela sugestão, vamos considerar esse tema tb.
