### ISSUE TITLE
Organizar horários dos LT

### ISSUE THREAD

**Issue by ketemartinsrufino** [cejs/cejsconf#6]
Temos que organizar os horários certinhos para não estourar o horário que reservamos na Uni7.

**Comment by monycky** [comment]
Horários LT

- Organização chegar as 8h para preparar o ambiente
- Organizar quem vai preparar o ambiente e material como microfone, sons, visual, etc 
 

08:30 - Credenciamento
09:00 - Apresentação do formato do evento 
09:10 - 1° talk
09:30 - 2° talk
09:50 - 3° talk
10:10 - 4° talk

-coffe 

10:30 - 5° talk 
10:50 - 6° talk
11:10 - 7° talk 
11:30 - 8° talk 

11:50 - Encerramento 

- Organizar um almoço/momento (after) de interação
